repos:
  - repo: local
    hooks:
    - id: unittest
      name: Unit tests
      entry: tox
      language: python
      always_run: true
      exclude: '.'  # don't pass filepaths to unittest
    - id: black
      name: Black linting
      entry: black
      language: python
      types: [python]
